//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RakeBack.RakeBackService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBaseOfArrayOfUserInfoYgFqSxnr", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class ResponseBaseOfArrayOfUserInfoYgFqSxnr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RakeBack.RakeBackService.UserInfo[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RakeBack.RakeBackService.UserInfo[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BelongToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchBankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchBankZHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateBankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InputPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsUpdatePassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IseableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPwdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Api {
            get {
                return this.ApiField;
            }
            set {
                if ((object.ReferenceEquals(this.ApiField, value) != true)) {
                    this.ApiField = value;
                    this.RaisePropertyChanged("Api");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankNumber {
            get {
                return this.BankNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNumberField, value) != true)) {
                    this.BankNumberField = value;
                    this.RaisePropertyChanged("BankNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BelongTo {
            get {
                return this.BelongToField;
            }
            set {
                if ((object.ReferenceEquals(this.BelongToField, value) != true)) {
                    this.BelongToField = value;
                    this.RaisePropertyChanged("BelongTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchBank {
            get {
                return this.BranchBankField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchBankField, value) != true)) {
                    this.BranchBankField = value;
                    this.RaisePropertyChanged("BranchBank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchBankZH {
            get {
                return this.BranchBankZHField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchBankZHField, value) != true)) {
                    this.BranchBankZHField = value;
                    this.RaisePropertyChanged("BranchBankZH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateBank {
            get {
                return this.CreateBankField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateBankField, value) != true)) {
                    this.CreateBankField = value;
                    this.RaisePropertyChanged("CreateBank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Createtime {
            get {
                return this.CreatetimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatetimeField, value) != true)) {
                    this.CreatetimeField = value;
                    this.RaisePropertyChanged("Createtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InputPerson {
            get {
                return this.InputPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.InputPersonField, value) != true)) {
                    this.InputPersonField = value;
                    this.RaisePropertyChanged("InputPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsUpdatePass {
            get {
                return this.IsUpdatePassField;
            }
            set {
                if ((object.ReferenceEquals(this.IsUpdatePassField, value) != true)) {
                    this.IsUpdatePassField = value;
                    this.RaisePropertyChanged("IsUpdatePass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iseable {
            get {
                return this.IseableField;
            }
            set {
                if ((object.ReferenceEquals(this.IseableField, value) != true)) {
                    this.IseableField = value;
                    this.RaisePropertyChanged("Iseable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginIdField, value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Updatetime {
            get {
                return this.UpdatetimeField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatetimeField, value) != true)) {
                    this.UpdatetimeField = value;
                    this.RaisePropertyChanged("Updatetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPhone {
            get {
                return this.UserPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPhoneField, value) != true)) {
                    this.UserPhoneField = value;
                    this.RaisePropertyChanged("UserPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPwd {
            get {
                return this.UserPwdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPwdField, value) != true)) {
                    this.UserPwdField = value;
                    this.RaisePropertyChanged("UserPwd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RakeBackService.IRakeBackService")]
    public interface IRakeBackService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRakeBackService/GetNewRakeBack", ReplyAction="http://tempuri.org/IRakeBackService/GetNewRakeBackResponse")]
        RakeBack.RakeBackService.ResponseBaseOfArrayOfUserInfoYgFqSxnr GetNewRakeBack(int pageSize, int pageIndex, System.Collections.Generic.Dictionary<string, string> conditions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRakeBackService/GetNewRakeBack", ReplyAction="http://tempuri.org/IRakeBackService/GetNewRakeBackResponse")]
        System.Threading.Tasks.Task<RakeBack.RakeBackService.ResponseBaseOfArrayOfUserInfoYgFqSxnr> GetNewRakeBackAsync(int pageSize, int pageIndex, System.Collections.Generic.Dictionary<string, string> conditions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRakeBackService/sdfsdf", ReplyAction="http://tempuri.org/IRakeBackService/sdfsdfResponse")]
        RakeBack.RakeBackService.UserInfo sdfsdf(int pageSize, int pageIndex, System.Collections.Generic.Dictionary<string, string> conditions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRakeBackService/sdfsdf", ReplyAction="http://tempuri.org/IRakeBackService/sdfsdfResponse")]
        System.Threading.Tasks.Task<RakeBack.RakeBackService.UserInfo> sdfsdfAsync(int pageSize, int pageIndex, System.Collections.Generic.Dictionary<string, string> conditions);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRakeBackServiceChannel : RakeBack.RakeBackService.IRakeBackService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RakeBackServiceClient : System.ServiceModel.ClientBase<RakeBack.RakeBackService.IRakeBackService>, RakeBack.RakeBackService.IRakeBackService {
        
        public RakeBackServiceClient() {
        }
        
        public RakeBackServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RakeBackServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RakeBackServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RakeBackServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RakeBack.RakeBackService.ResponseBaseOfArrayOfUserInfoYgFqSxnr GetNewRakeBack(int pageSize, int pageIndex, System.Collections.Generic.Dictionary<string, string> conditions) {
            return base.Channel.GetNewRakeBack(pageSize, pageIndex, conditions);
        }
        
        public System.Threading.Tasks.Task<RakeBack.RakeBackService.ResponseBaseOfArrayOfUserInfoYgFqSxnr> GetNewRakeBackAsync(int pageSize, int pageIndex, System.Collections.Generic.Dictionary<string, string> conditions) {
            return base.Channel.GetNewRakeBackAsync(pageSize, pageIndex, conditions);
        }
        
        public RakeBack.RakeBackService.UserInfo sdfsdf(int pageSize, int pageIndex, System.Collections.Generic.Dictionary<string, string> conditions) {
            return base.Channel.sdfsdf(pageSize, pageIndex, conditions);
        }
        
        public System.Threading.Tasks.Task<RakeBack.RakeBackService.UserInfo> sdfsdfAsync(int pageSize, int pageIndex, System.Collections.Generic.Dictionary<string, string> conditions) {
            return base.Channel.sdfsdfAsync(pageSize, pageIndex, conditions);
        }
    }
}
